# Generated by Django 4.0.6 on 2024-06-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0008_rename_decripcion_genero_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='genero',
            new_name='genero_p',
        ),
    ]
