# Generated by Django 4.0.6 on 2024-06-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0009_rename_genero_pelicula_genero_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='genero_p',
            new_name='genero',
        ),
    ]
