# Generated by Django 4.0.6 on 2024-06-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0011_genero_foto_pelicula_portada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='portada',
            new_name='foto',
        ),
    ]
