# Generated by Django 4.0.6 on 2024-06-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0012_rename_portada_pelicula_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='foto',
            new_name='portada',
        ),
    ]
