# Generated by Django 4.0.6 on 2024-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0013_rename_foto_pelicula_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='portada',
        ),
        migrations.AddField(
            model_name='director',
            name='portada',
            field=models.FileField(blank=True, null=True, upload_to='directores'),
        ),
    ]
