# Generated by Django 4.0.6 on 2024-06-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0014_remove_pelicula_portada_director_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='postulantes'),
        ),
    ]
