# Generated by Django 4.0.6 on 2024-06-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0015_genero_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='generos'),
        ),
    ]
