# Generated by Django 5.0.6 on 2024-07-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0016_alter_genero_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='director',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='directores/'),
        ),
    ]
