# Generated by Django 5.0.6 on 2024-07-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0018_cine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='telefono',
            field=models.CharField(default='', max_length=150),
        ),
    ]
