# Generated by Django 5.0.6 on 2024-07-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0019_alter_cine_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='generos/curriculums/'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='generos/fotos/'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
