# Generated by Django 5.0.6 on 2024-07-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0020_genero_estado_alter_genero_curriculum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='curriculum',
        ),
    ]
