# Generated by Django 5.0.6 on 2024-08-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0022_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='director',
            name='portada',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='estado',
        ),
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='directores'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.FileField(blank=True, null=True, upload_to='portadas'),
        ),
        migrations.AlterField(
            model_name='cine',
            name='direccion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cine',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='director',
            name='dni',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='genero',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='generos'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
