databases:
  - name: servidorAdrian
    plan: free
    databaseName: dbcine
    user: adrian

services:
  - type: web
    plan: free
    name: cineUTC
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUTC.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorAdrian
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutc-b1lz.onrender.com

# set DATABASE_URL=postgresql://adrian:cVYvhiUAWI3zHfUOSnoXu8gGwt3GX8jg@dpg-cqlpl8d6l47c73fj7vtg-a.oregon-postgres.render.com/dbcine_4m9u

